name: Create translation pull request J5

on:
  workflow_dispatch:

  schedule:
    - cron:  '37 7 * * *'

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GPAT }}
          repository: heelc29/joomla-cms
          fetch-depth: 0
          ref: 5.0-dev

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch latest cms changes
        run: |
          git remote add upstream https://github.com/joomla/joomla-cms.git
          git fetch upstream
          git checkout --progress --force -B translation-j5 refs/remotes/origin/5.0-dev
          git reset --hard upstream/5.0-dev

      - name: Fetch and extract translations
        run: |
          cd ..
          wget -nv "https://github.com/joomla/core-translations/archive/refs/heads/main.zip"
          unzip main.zip

      - name: Syncing directories
        run: |
          cd ..
          SYNC_VERSION="v5"

          SYNC_PATH="installation/language/"
          echo ${SYNC_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete --exclude="*en-GB*" core-translations-main/joomla_${SYNC_VERSION}/translations/core/${SYNC_PATH} joomla-cms/${SYNC_PATH}

      - name: Update static error pages
        run: |
          npm ci --ignore-scripts && node build/build.js --build-pages

      - name: Create commit
        run: |
          git config user.name Translation Bot
          git config user.email release+translation-bot@joomla.org
          git add .
          git commit -m "Language update"
          git push origin HEAD --force
